### PR TITLE
Remove obsolete che-codestyle-intellij.xml

### PR DESCRIPTION
**Pull request by azatsarynnyy**
Remove obsolete _che-codestyle-intellij.xml_
Rename _che-codestyle-intellij-new.xml_ -> _che-codestyle-intellij.xml_

@evoevodin @skabashnyuk

### CODE REVIEW

**Comment by voievodin** [comment]
+1

**Comment by skabashnyuk** [comment]
-1 I have no idea what che-codestyle-intellij-new.xml  it is.

**Comment by azatsarynnyy** [comment]
This is the updated/improved codestyle for IntlliJ IDEA that was added by @evoevodin and that we're already using more than 2 month.
https://github.com/codenvy/codenvy-dev-resources/commit/fb32df35fb5fa78a1318f4cce578d82f9fd4506a
I believe that we must have there only one actual codestyle for IntelliJ IDEA.
Don't you agree?

**Comment by skabashnyuk** [comment]
Never heard about discussion of new codestyle. If someone wants to change existing it can be easily added by PR.

**Pull request closed without merging**
